### PR TITLE
Fix: Git and GitHub Collabo | 1st Issue Ticket Task | Working with GitHub web UI

### PR DESCRIPTION
**Pull request by Goodnews-code**
#### This pull request makes the following changes

* Fix: #50

#

#### General checklist

- [x] My pull request adheres to the [Collabo Community pull request guidelines](https://docs.collabocommunity.com/pull-request-guidelines).
- [x] I have read and understood the **Pull request guideline extension** section found at the bottom of this pull request description/body.
- [x] I have replaced the dummy text under the subheading **Testing checklist** below with the testing checklist from the issue ticket I'm working on.

#

#### Testing checklist

- [x] My branch for this task assignment is created from the develop branch, and the name of my branch is a mix of @ and my GitHub user name as specified in the issue ticket.
- [x] The folder with its name having a mix of @ and my GitHub user name has been created in the root of the @gitcollab-learn folder.
- [x] A file called gitcollab-1st-task.md is in the root of my newly created folder.
- [x] The gitcollab-1st-task.md file uses the content of [the README.md file found at the root of the @gitcollab-learn folder](https://github.com/collabo-community/use-me-for-experiments/blob/develop/%40gitcollab-learn/README.md). I have also followed the directions in there to replace text where necessary.
- [x] I certify that I ran my checklist.

#

#### Pull request guideline extension

> [!NOTE]  
> Do not remove this note and the sections below. This talks about extra things to take note of, in addition to the directions given in the Collabo Community pull request guidelines.

We appreciate the time taken to help tackle issue tickets within the Collabo Community. Please go ahead to submit your pull request even if it is not yet completed, and push to the pull request actively. This will allow us to know that you have not abandoned the issue ticket. However, you should only alert reviewers about your pull request as explained below, to avoid flooding their GitHub notifications unnecessarily.

"Ready for review" implies that things are working as expected, according to how it is specified in the issue ticket you are working on. Ensure that you test the code that you are working on, that it works as expected. Don't just request for review when your pull request is not yet done and working.

The only time you should be making people review something incomplete is: if you want to show them what's not working, so that they can send help or guidance. If this is the case, be explicit about this in our Discord community or in the comment of your pull request (after you have submitted the pull request).

#

**Requesting review**: For this repository, the review team to request review from is the **`@collabo-community/maintainers`** team. Once your pull request is ready for review, select this review team from the reviewers dropdown on this pull request. If you don't have access to the reviewer's dropdown, tag this review team in the comment of this pull request.

### CODE REVIEW

**Comment by Goodnews-code** [comment]
# Hi,  @collabo-community/maintainers.

## This PR is ready for review.

**Comment by Ifycode** [comment]
You don't need to format your comment as an header with markdown @Goodnews-code 
I see you did same thing for the comment on the issue. Normal text will do. That way tagging the maintainer's team will work.
We didin't receive a notification for your PR, due to the formatting I think. This is just me randomly checking and finding your PR (and comment on the issue ticket).

**Review by Ifycode — APPROVED** [review]
Great job @Goodnews-code 🥳🎉
Really cleanly and nicely done. You are a natural 😃
Approved!

#

Please check back later in the week. The link for the next task would have been added to the list by then.

**Comment by Goodnews-code** [comment]
Okay ma, noted ma.

Thank you so much ma, i'd take note of that.

**Pull request merged**
